# Generated by Django 5.2.6 on 2025-10-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFile',
            new_name='ExcelUpload',
        ),
    ]
